const product = {
    name: "Ball pen",
    rating: 5,
    offers: "%5",
    price: 250,
};

console.log(typeof product["price"]);

console.log("Question 2 - create a const object called profile to store information store in the picture");

const profile = {
    username: "shradha kappra",
    No_ofpost: 195,
    followers: "569k",
    isfollow: true,
};
console.log(profile["username"]);
console.log(typeof profile.isfollow);